### PR TITLE
Loosen docPath validation to string

### PR DESCRIPTION
**Pull request by raineorshine**
I have a simple eslint plugin with a single rule and would like to set the docPath to `README.md`:

```js
{
  "docPath": "README.md"
}
``` 

Unfortunately the `path` validation prevents this. Would you be open to loosening the validation for `docPath` to `string`?

Here's the plugin:
https://github.com/raineorshine/eslint-plugin-export-default-identifier

### CODE REVIEW

**Comment by edg2s** [comment]
That seems reasonable, the tests & README will need updating though.

**Comment by edg2s** [comment]
Actually I would suggest this as a workaround, set your docpath to:
```
"docPath: "{name}/../README.md"
```

I think we should support a single README mode, but that it should allow things like concatenating multiple outputs into a single file.

**Comment by raineorshine** [comment]
Okay, that's fair if you would like to enforce `{name}` for most users.

**Comment by edg2s** [comment]
Thanks for the idea though, I've filed it as #90.

**Pull request closed without merging**
